### ISSUE TITLE
Tool breaks when using 'version' dart package

### ISSUE THREAD

**Issue by rolandgeider** [M123-dev/fastlane-plugin-flutter_dart_version_manager#2]
The tool breaks pubspec.yaml when you have the [version](https://pub.dev/packages/version) dart package as a dependency which parses version strings. Not only does it update its pinned version as well, it also removes the indentation whitespaces, making further build steps complain that the version key is duplicated (because now it is)

As an example, see [this run](https://github.com/wger-project/flutter/runs/4137670354?check_suite_focus=true)

A simple solution is probably to just check for "version:" without any whitespaces

**Comment by M123-dev** [comment]
Thanks for your feedback @rolandgeider the bug should have been fixed by #4 . The changes are now also already published on ruby-gems under version 0.1.5. If there are other things just let me know.

**Comment by rolandgeider** [comment]
Thank you for fixing this so quickly
